### ISSUE TITLE
Challenge - Bring Off Chain Payments to WT with Liquidity Network

### ISSUE THREAD

**Issue by thibmeu** [windingtree/wt-hackathon#10]
## BUILDLing

Waiting 15 seconds for a transaction to be confirmed is not the best user experience you can provide. Users require their transactions to be fast, cheap and secure.

Integrate the [Liquidity network](https://liquidity.network) payment solution into Winding Tree to turn instant and free payments into a reality. The system should allow carrier to setup their wallet and clients to pay online. Interaction should be possible using API.

Get inspiration by looking at alternative booking websites’ and the payment systems already used and make blockchain payments as simple to use. Liquidity provides you with a cross platform invoice system, available on iOS, Android and desktop.

## Judging criteria
In order to ensure impartiality, every criteria is assessed multiple times and the prize rewarded accordingly.

### User experience
We are looking for clean, intuitive, and an easy to follow user experience. Taking care of the medium is another key factor for happy users and judges.

### Execution
Your code is readable, documented and ready to be integrated by other projects.

### Wow
Some projects are like no others - we reward originality!

## Resources
You can find all the resources at the Liquidity Kit Repo: https://github.com/liquidity-network/liquidity-sdk.

Here’s a link to all registered wallets on our current Liquidity hub: https://beta.liquidity.network/admission/?format=json

Here’s a link to the transaction history of a particular Liquidity wallet: https://beta.liquidity.network/audit/627306090abaB3A6e1400e9345bC60c78a8BEf57/?format=json

If you have any questions feel free to reach our team via Telegram at [@liquiditydevelopers](https://t.me/liquiditydevelopers) or come to say hi to [thibmeu](https://github.com/thibmeu).

**Comment by ligi** [comment]
I am thinking about accepting this challenge as I think it could solve a pain point I already often had when traveling. I like to stay in hostels and often you have to pay for small things (bicycle rental, laundry, staying one more night ..) - a payment hub like this could help here to make this process more friction-less. And when booking the ho(s)tel via winding-tree you already have their address. 
If anyone wants to join the fun - you can find my contact details here: https://ligi.de - I think I would start by integrating liquidity network into the mobile wallet I am maintaining - https://walleth.org as I think this makes most sense when traveling. If you want to rent a bike - just pull out your phone and sign that you are willing to spend XX DAI for it.

**Comment by ligi** [comment]
Also @thibmeu if you have some time it would be great to ask some question - my main one at the moment: how to use it on a testnet? I prefer to not litter the main-net when testing - but currently it always states "Mainnet". 

![liquidity](https://user-images.githubusercontent.com/111600/47432952-b1f20400-d79f-11e8-8a4d-437fa818b753.png)
