### ISSUE TITLE
Ticket refund in case of partner carrier insolvency

### ISSUE THREAD

**Issue by rakahbus** [windingtree/wt-hackathon#16]
In case a passenger with an airline ticket is affected by the insolvency of one of its interline partners. some airlines make a full refund of the unused part of the ticket including taxes. The current process is as follows
1. Passenger contacts travel agency where his ticket was purchased
2. Travel agency submits refund application (RA) via BSP Link to the carrier according to its Refund Policy.
3. Airline approves RA and processes the refund via BSP report; for ARC markets refunds will be processed by ACM or authorized via GDS directly
4. Travel agency reimburses the refunded amount to the passenger.

The whole process can be automated with an immediate refund capability using an ethereum based smart contract

**Comment by rakahbus** [comment]
The code given below is subject to change and still posses some errors

https://gist.github.com/rakahbus/b4ccca6f7217cb094774cd91eeeea98a

**Comment by rakahbus** [comment]
The code given below subject to some errors, but one could have fair understanding about the process flow.
https://gist.github.com/700248c93be2ea49e815dadba74d1e74.

**Comment by JirkaChadima** [comment]
Closing this, superseeded by #27
