### ISSUE TITLE
Idea - Distributed Storage

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#2]
Optimize/Improve the use of distributed storages (if t is possible swarm) on WT solutions.

- Add the use of swarm provider, we only support one swarm provider for now, we want to support multiple ones as fallback solutions, so in case the main provider is down it will try to get the information from the next one.
- Access files via ens and not unique hash ids. ENS has a content resolver that can be used for resources hosted in swarm, integrated ens resources in the existent WT API to get the content from hotelname.windingtree.eth.
- Add mutable resource updates on WT APIS, right now the resource that is being pointed by the hash id is not mutable, which means that we cannot change it directly in swarm and every time we want to change the content we need to deploy a new file, get the hash id and register the new URI in the wt index smart contract. With the use of mutable resources, we can avoid all this and directly change the content hash in swarm. reference: https://swarm-guide.readthedocs.io/en/latest/usage.html#mutable-resource-updates.

### Mentors
Elad from swarm: https://github.com/justelad
Makoto from ens: https://github.com/makoto

**Comment by skylarweaver** [comment]
I'm interested in hacking this challenge — if anyone else is up for it find me!
