### ISSUE TITLE
Hackathon Post Mortem - Technical Feedback - Dev environment

### ISSUE THREAD

**Issue by metasimian** [windingtree/wt-hackathon#30]
For WT blockchain hacking, it would have helped to have been provided recommendations for an end-to-end testing environment. 

Our project was the following: https://github.com/windingtree/wt-hackathon/blob/master/submissions/2018/WipuHotelCrossSell.md

- Initial environment was solc + geth running on Linux for Windows / Ubuntu. 
- We quickly moved to Truffle + Ropsten + MyEtherWallet.  It expedited build/migrate, but testing failed (we were able to create new Hotel contracts, but the new function to set partners failed). 
- We were able to get the code working by copying to Remix + Ropsten for coding/compiling/testing (unfortunately it worked AFTER the end/submission deadline :( ). 

Assumption is that MyEtherWallet is buggy and/or not entirely compliant and that the failing testing was due to the testing tool vs. the code.

**Comment by JirkaChadima** [comment]
Closing for now, will be dealt with as part of #31
