### ISSUE TITLE
#11 WT Proof of trust

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#32]
Propose how to verify how trustworthy is an actor registered in the Winding Tree public key registry.
The goal with this is to verify easily the authenticity of the data that is transferred between different actors in the WT platform.

Ideas we had so far in the core dev team:
- Know Your Custommer
- ACME DNS / ENS
- Trust level based on Líf deposit + current Líf price + statistic analysis
- Token Currated Registry
- Peer to Peer - trust provided by one identity to another
- Connector to some existing identity / reputation system
- Provable business history with an already established partner

Reference:
- https://ens.domains/
- https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#sign
- https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#recover
- https://medium.com/@tokencuratedregistry/a-simple-overview-of-token-curated-registries-84e2b7b19a06

**Comment by kvakes** [comment]
I would also specify that KYC could be done via EV SSL: https://en.wikipedia.org/wiki/Extended_Validation_Certificate

**Comment by JirkaChadima** [comment]
We need a proper documentation on trust clues for this to work. This could be vey exciting!

**Comment by AxelAtPeakwork** [comment]
I'm up to be part of this challenge. Any other takers?
