### ISSUE TITLE
Booking, Pricing & Availability manager (simple PMS)

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#33]
Create an app that can be used by WT users that will allow managing bookings (list, accept, reject), update rate plans and availability.
If you decide to work on this we recommend you to use the wt-write-api and wt-js-libs.

https://github.com/windingtree/wt-write-api
https://github.com/windingtree/wt-js-libs

**Comment by kvakes** [comment]
I would recommend promoting existing standards like HTNG and OTA instead of WT.

**Comment by menschikov** [comment]
If I understand right, this app communicates with WT only when registering in index and posting it's URI to it's booking API. Correct?

**Comment by JirkaChadima** [comment]
The original thought was to create a PMS to manage hotel property on WT. If you (as in hotel) are using OTA/HTNG, you probably already have a PMS. We wanted to create a tool (ideally an actual dapp) for managing WT data directly. It doesn't make sense to create a Winding Tree PMS that's using something else than the https://github.com/windingtree/wt-hotel-schemas. If we strip the data format from this PMS, it becomes an onboarding app for registering a hotel. It might be a challenge, but it's something else.
