### ISSUE TITLE
#4 Package Booking

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#37]
Let Winding Tree platform OTAs to book multiple travel services with one transaction

**Steps:**
- [Learn about WT](https://developers.windingtree.com/)
- Check our proposal about [ancillary settlement](https://github.com/windingtree/developers/blob/intro/book/use-cases/airlines/ancillary-settlement.md) and package booking (below in notes), pick some direction
- Pick several travel products from different suppliers on the platform
- Adjust Winding Tree APIs or create new API to perform multiple bookings with one transaction
- Perform that transaction

**Package booking notes**
Every online travel agency allows the users to book hotels, flights, car rental, activities at once, this should be even faster and more simple with a more automated and decentralized system like we are trying to build in WT. All the "inventory" in WT will be published following a base standard, this will allow different type of inventory to be booked at once, one TX to book everything.

For the hackathon we will have hotel data available for testing, the best way to test this would be to find a way to publish different type of inventory (maybe we already have flight inventory for testing at the moment of the hackathon) and find a way to send one TX to the wt-read-api to book a hotel room + something else.

**Comment by kvakes** [comment]
Yes, but read/write API should not be used

**Comment by AugustoL** [comment]
@kvakes ideally yes, all the logic and computation should happen in the smart contract level. But since every API is connected to the eth network it can be used to push the txs into the network.
