### ISSUE TITLE
#8 Lif Loyalty 

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#39]
Lif Loyalty - design a loyalty system for the platform where LIf is unified loyalty point for all types of businesses

**Steps:**
- [Learn about WT](https://developers.windingtree.com/)
- Learn our proposal for Lif Loyalty
- Adjust it or create own proposal, make a diagram
- Confirm your proposal with business feedback and facts

**Notes**
Design a loyalty token economic that can be used in the WT platform by issuing a distribution LIF tokens that can be used to book specific offers.
One of the ways to do this is to allow hotels and airlines to have a token pool, where they can issue a fixed or dynamic amount of tokens (depending on how much the user is spending) on each booking that they receives.
The hotels and airlines can create special offers where the users can book with a discount if they also send tokens, and this tokens can go directly to the token pool. Automating the complete process and keeping the customer, win-win scenario.

**Comment by kvakes** [comment]
This is a business topic, I've talked to hotels about it, they are confused about how it's gonna work. Developers are confused by confused business people, too.

**Comment by AugustoL** [comment]
I see it as both, technical and business, both of them important to build. Lot of cool stuff to be done in loyalty.

**Comment by renjithpta** [comment]
**Team IBS** trying to make a solution which helps to create an ecosystem using LIF  for implementing Loyalty.

We provide freedom of choice to the customers by redeeming loyalty points as Winding tree LIF and can create an ecosystem to make use of LIF to buy ancillary provided by Flights, Hotels or Retails. Conversion of customer loyalty point will be based on smart contact.

 An offline model of loyalty transaction will be followed to reduce the transaction cost.
