### ISSUE TITLE
Travel Agencies Index

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#40]
Propose design and infrastructure of how an index of travel agencies can be integrated into WT, these agencies can distribute and resell the inventory published in the hotel and airline indexes.

**Comment by kvakes** [comment]
I don't understand this

**Comment by JirkaChadima** [comment]
I *think* this can possibly be transformed into a work spanning on top of https://github.com/windingtree/wt-ota-schemas and https://github.com/windingtree/wt-contracts/blob/develop/contracts/OtaDirectory.sol ?
