### ISSUE TITLE
Meta TXs on WT

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-hackathon#41]
The transactions in ethereum have to be "crafted", signed, and payed. But this doesn't mean that the same actor needs to do this three actions, here is where meta transactions comes to make everything easier, allowing a transaction to be created by a dapp, signed by a user and payed by a smart contract relay.

This is something ideal to integrate with the WT apis.

Reference:
https://medium.com/@austin_48503/ethereum-meta-transactions-90ccf0859e84
https://medium.com/gitcoin/native-meta-transactions-e509d91a8482
https://github.com/ethereum/EIPs/issues/1776
https://github.com/tsuzukit/meta-transaction
https://medium.com/uport/making-uport-smart-contracts-smarter-part-3-fixing-user-experience-with-meta-transactions-105209ed43e0

**Comment by kvakes** [comment]
I like this, but meta txs are a tool, not the means to achieve something.

**Comment by JirkaChadima** [comment]
@kvakes It could however be a tool used for a challenge to create an app that would create an Org.ID for you for free (i. e. gas paid for by someone else).
