### ISSUE TITLE
#1 Blockchain based Metasearch

### ISSUE THREAD

**Issue by menschikov** [windingtree/wt-hackathon#45]
Create a simple metasearch - a website that lists all hotels accessible via Winding Tree platform in chosen location and redirect visitors to hotels’ website

**Steps:**
- [Learn about WT](https://developers.windingtree.com/)
- Train your service to find hotels registered on the platform and get their metadata 
- Make your service show hotels by location and their metadata data on website
- Make your service redirect visitors to hotels website (url received in hotel Metadata)
- Make REST API for this service to allow OTAs ask you City and Location and return them list of hotel names with URLs
- When you succeed and have time - pick [#2](https://github.com/windingtree/wt-hackathon/issues/46) Challenge to make booking or [#7](https://github.com/windingtree/wt-hackathon/issues/50) challenge to show only companies with verified websites

**Notes**
Check our Search API and Hotel Explorer to get insights

**Comment by menschikov** [comment]
@kvakes please approve and add labels

**Comment by myroslava72** [comment]
Team Roadmap will be working on this.
