### ISSUE TITLE
#2 Sell a room

### ISSUE THREAD

**Issue by menschikov** [windingtree/wt-hackathon#46]
Make your OTA to allow travellers to book a room in a hotel accessible via platform

**Steps:**
- [Learn about WT](https://developers.windingtree.com/)
- Register your OTA on the platform and get ID
- Train your OTA to find specific hotel on the platform and connect to their API 
- Make your OTA to get list of available rooms
- Make successful booking, sign it with your signature on the platform
- When you succeed - pick Metasearch challenge and train your service to find hotels and connect to them.

**Comment by myroslava72** [comment]
Team Roadmap will be working on this.
