### ISSUE TITLE
#3 ORG.ID explorer

### ISSUE THREAD

**Issue by menschikov** [windingtree/wt-hackathon#47]
Build a webpage that lists organisations registered with Winding Tree and displays their computed trust value

**Steps**
- [Learn about WT](https://developers.windingtree.com/)
- Design your own proposal for trust system on the platform or take one of ours
- Simulate some companies with different level of trust
- Make a webpage that scans platform and shows companies with defined level of trust
- Additionally you can represent them on the map
- When you finish that - try [#6](https://github.com/windingtree/wt-hackathon/issues/49) to let hotels receive transactions from trusted OTAs

**Comment by jmoujaes** [comment]
Gonna tackle this w/Martin
