### ISSUE TITLE
#5 Authorization APP

### ISSUE THREAD

**Issue by menschikov** [windingtree/wt-hackathon#48]
Build user friendly Authorization service

**Steps:**
- [Learn about WT](https://developers.windingtree.com/)
- Make a safe tool that allows a company owner to easily get an ORG.ID
- Make a safe tool that allows a company owner to easily fill their JSON datafile on the platform
- Make a safe tool that allows company managers to create their digital signatures
- Let company owner link those signatures with the company

**Comment by jamesoshea** [comment]
The team from HolidayPirates will work on this challenge
