### ISSUE TITLE
#7 Website verification

### ISSUE THREAD

**Issue by menschikov** [windingtree/wt-hackathon#50]
Make a tool that verifies if the website of a company registered on Winding Tree really belongs to that company

**Steps:**
- Learn about WT and trust
- Check what is stored in company’s JSON on the platform
- Design a rule how to verify that URL stored in company’s JSON belongs to the company
- Make a tool that receives company’s ID and replies with TRUE if the domain is verified.
- Make a simple API for that

**Comment by AxelAtPeakwork** [comment]
I'm up to be part of this challenge. Any other takers?
