### ISSUE TITLE
PIRATETREE

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hackathon#53]
**Contact: Bojan Smudja <b.smudja@piratetech.rs>**

**INTRO ­ Our team**
HolidayPirates Group ­ travel inspiration website operating on 10 major world market providing best human and automatic curated deals using our partners API, like Kayak, booking, Kiwi,etc...

**Problem definition**

Lack of trust ­ complicated user flow from the user being inspired to booking on which we
directly can not have an impact, as:

  - The user gets redirected from our site to partner payment gateways;
  - Lack of tracking of the bookings;
  - Price fluctuation due to a long booking process;
  - Travel groups splitting booking costs;
  - Inconsistency in partners payment pages.

**Solution proposal**

Achievement:
  - Offering unique experience and simple user flow in the least possible number of steps from inspiration to booking;
  - Venmo for travel groups.

How to get there:
  - To provide a universal open standard for the deal information and booking confirmation;
  - To use Windingtree authentication and trust mechanisms to prove that a certain deal is available from a certain partner;
  - OTAs and meta aggregators can redirect users directly to a provider’s booking/payment page;
  - The information needed to check the availability of an offer is included in the request from the OTA to the provider.

https://drive.google.com/open?id=1J8rcAE3OTaW-ooKBXO9TprME_211Iwlv

**Comment by bojansmudja** [comment]
After consideration, our team decided to narrow the idea of PIRATETREE to develop more only part of VENMO for travel groups regarding time deadline.

**Comment by bojansmudja** [comment]
Business Process flow proposal 1 attached: 
[BP flow.pdf](https://github.com/windingtree/wt-hackathon/files/3359034/BP.flow.pdf)

**Comment by bojansmudja** [comment]
Proposal of API calls for simplified proces: 
[WT Hackathon-Page-2.pdf](https://github.com/windingtree/wt-hackathon/files/3359622/WT.Hackathon-Page-2.pdf)

**Comment by bojansmudja** [comment]
Anita - User flow perspective: 
![User Flow](https://user-images.githubusercontent.com/13235419/60673895-c3cc9080-9e70-11e9-821e-fba2d9f4fe96.png)
