### ISSUE TITLE
Business Idea - Trusted Data Storage

### ISSUE THREAD

**Issue by jmoujaes** [windingtree/wt-hackathon#57]
Contact: Jason M. -- jmoujaes@gmail.com

**The Scenario**
A hotel booking portal CUSTOMER tells hotel HOTEL that they want to book 5 rooms.
HOTEL says great, it will be 5000 dollars.
CUSTOMER says great, here is 5000 dollars.

Both parties get a receipt of this transaction.  
They are both responsible for storing this receipt for their records, and in case of disputes in the future.  

**The Problem**  
People lose receipts.  

**The Solution**  
1. Store receipts for companies in a secure and resilient fashion.  
2. Send receipts to their owners when they request them.  
3. ???
4. $ Get $$ Paid $

**Further Ideas**  
Expand into Content Delivery.
Expand into Marketing/Advertising.

**Comment by jmoujaes** [comment]
@JirkaChadima
Please let me know if I should modify this in any way

**Comment by JirkaChadima** [comment]
@jmoujaes It looks great. Maybe some contact e-mail is missing

**Comment by jmoujaes** [comment]
Thanks! Will update.
