### ISSUE TITLE
Idea - Private offers

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hackathon#8]
Winding Tree is an open platform, but sometimes, you need to make some of your data private. Maybe it's confidential, or maybe it's just not meant to be seen by everybody. With the use of [homomorphic encryption](https://en.wikipedia.org/wiki/Homomorphic_encryption), you can transfer the data through the system without the fear of them being decrypted by unauthorized parties while still allowing authorized parties to read them.

Your goal would be to implement such feature for hotel pricing. Let's imagine you are a hotel chain with 5 hotels and you have an agreement with some large company whose employees visit your country very often. And all of those employees are staying only in your hotels. So you want to give the large company a discount, but don't really want to make it publicly known. So as a hotel, you want to create a private offer that can be decrypted only by a system run by that large company.

Now imagine, that you are partnered with multiple large companies and want to treat them in the exact same way with the exactly same discount.

**Resources**

- [Homomorphic encryption](https://en.wikipedia.org/wiki/Homomorphic_encryption)
- [Zero-knowledge proof](https://en.wikipedia.org/wiki/Zero-knowledge_proof)
- Proxy re-encryption, https://www.nucypher.com/

**Comment by kvbik** [comment]
ping @jMyles or @KPrasch if you want to use http://github.com/nucypher/nucypher-kms
